VM4 Simulator: inst.c File Reference
inst.c File Reference
#include "vm4.h"
Functions
int decode (const char *op_code, uint16_t address)
void hlt (void)
void lod (uint16_t addressFrom)
void str (uint16_t addressTo)
void add (uint16_t addAddress)
void nop (void)
void nnd (uint16_t nndAddress)
void cxa (void)
void jmp (uint16_t jumpAddress)
void printReg (void)
void setXOR (void)
Variables
uint16_t regPC = 0
nibble regA
uint16_t regMEM = 0
nibble regSTAT
Function Documentation
void add (uint16_t addAddress)
Definition at line 80 of file inst.c.
References _nibble::data, MAINMEM, and regMEM.
Referenced by decode().
{
     regMEM = addAddress;
     uint8_t temp1 = regA.data;
     uint8_t temp2 = MAINMEM[addAddress].data;
     uint8_t result = temp1 + temp2;
     regA.data = result & 0xF;
     //Set overflow bit
     if((temp1 & 0x8) && (temp2 & 0x8) && !(result & 0x8)){
         regSTAT.data |= 0x8;
         regSTAT.data ^= (result & 0x8);
         }
     else if(!(temp1 & 0x8) && !(temp2 & 0x8) && (result & 0x8)){
         regSTAT.data |= 0x8;
         regSTAT.data ^= (result & 0x8);
         }
     else
         regSTAT.data &= 0x7;
     //If there was a carry out
     if(result & 0x10)
         regSTAT.data |= 0x2;
     else
         regSTAT.data &= 0xD;
 }
void cxa (void)
Definition at line 118 of file inst.c.
References _nibble::data.
Referenced by decode().
               {
     regA.data = regSTAT.data;
 }
int decode (const char * op_code, uint16_t address)
Definition at line 26 of file inst.c.
References add(), cxa(), hlt(), jmp(), lod(), nnd(), nop(), and str().
Referenced by mainloop().
 {
     if(!strcmp(op_code, "HLT"))
     {
         hlt();
     }
     else if(!strcmp(op_code, "LOD"))
     {
         lod(address);
     }
     else if(!strcmp(op_code, "STR"))
     {
         str(address);
     }
     else if(!strcmp(op_code, "ADD"))
     {
         add(address);
     }
     else if(!strcmp(op_code, "NOP"))
     {
         nop();
     }
     else if(!strcmp(op_code, "NND"))
     {
         nnd(address);
     }
     else if(!strcmp(op_code, "JMP"))
     {
         jmp(address);
     }
     else if(!strcmp(op_code, "CXA"))
     {
         cxa();
     }
     return 0;
 }
void hlt (void)
Definition at line 65 of file inst.c.
References _nibble::data.
Referenced by decode().
               {
     regSTAT.data |= 0x1;
 }
void jmp (uint16_t jumpAddress)
Definition at line 122 of file inst.c.
References _nibble::data, regMEM, and regPC.
Referenced by decode().
{
     regMEM = jumpAddress;
     if(regA.data == 0)
         regPC = jumpAddress;
 }
void lod (uint16_t addressFrom)
Definition at line 69 of file inst.c.
References MAINMEM, and regMEM.
Referenced by decode().
{
     regMEM = addressFrom;
     regA = MAINMEM[addressFrom];
     //setXOR(); No longer doing this in load
 }
void nnd (uint16_t nndAddress)
Definition at line 111 of file inst.c.
References _nibble::data, MAINMEM, and regMEM.
Referenced by decode().
{
     regMEM = nndAddress;
     regA.data &= MAINMEM[nndAddress].data;
     regA.data = ~regA.data;
     //setXOR();
 }
void nop (void)
Definition at line 107 of file inst.c.
Referenced by decode().
               {
 }
void printReg (void)
Definition at line 129 of file inst.c.
References _nibble::data, regMEM, and regPC.
Referenced by mainloop().
                    {
     printf("A: %x\n", regA.data);
     printf("PC: %x\n", regPC);
     printf("MEM: %x\n", regMEM);
     printf("STAT: %x\n", regSTAT.data);
 }
void setXOR (void)
Definition at line 138 of file inst.c.
References _nibble::data.
                  {
         nibble temp;
         temp.data = regA.data ^ regSTAT.data;
         temp.data &=  0x8;
         if(temp.data == 0x8)
             regSTAT.data |= 0x2;
         else
             regSTAT.data &= 0xD;
 }
void str (uint16_t addressTo)
Definition at line 75 of file inst.c.
References MAINMEM, regA, and regMEM.
Referenced by decode(), and tobitstr().
{
     regMEM = addressTo;
     MAINMEM[addressTo] =  regA;
 }
Variable Documentation
nibble regA
Definition at line 18 of file inst.c.
Referenced by mainloop(), and str().
uint16_t regMEM = 0
Definition at line 19 of file inst.c.
Referenced by add(), jmp(), lod(), nnd(), printReg(), and str().
uint16_t regPC = 0
Definition at line 17 of file inst.c.
Referenced by jmp(), main(), mainloop(), and printReg().
nibble regSTAT
Definition at line 20 of file inst.c.
Referenced by mainloop().