VM4 Simulator: mainB.c File Reference
mainB.c File Reference
#include "vm4B.h"
Functions
int main (int argc, char **argv)
int mainloop (void)
int shutdown (int err)
Function Documentation
int main (int argc, char ** argv)
Definition at line 21 of file mainB.c.
References initMem(), mainloop(), and VERSTR.
{
     int i;
         int status;
         printf("%s starting up...\n", VERSTR);
         printf("Command line arguments:\n");
         printf("~q: Quit, ~pm lower upper: Prints mem between lower and upper\n");
         printf("~pr: Prints register contents\n");
         for(i = 1; i < argc; i++)
         {
                 if(argv[i] != NULL)
                 {
                         printf(" %s", argv[i]);
                 }
         }
     initMem();
         puts("");
         status = mainloop();
         return status;
 }
int mainloop (void)
Definition at line 48 of file mainB.c.
References _nibble::data, decode(), printMem(), printReg(), regA, regSTAT, and setBoot().
Referenced by main().
                   {
     char op_code[100];
     uint16_t instAddr;
     uint16_t topAddr;
     char run = 1;
     char in[100];
     regA.data = 0;
     regSTAT.data = 0;
     setBoot();
     while(run){
         printf("Input: ");
         fgets(in, 99, stdin);
         sscanf(in, "%s %hu %hu", op_code, &instAddr, &topAddr);
         //Process input
         if(!strcmp(op_code, "~q")){
             printf("Halting");
             run = 0;
         }
         else if(!strcmp(op_code, "~pm")){
             printMem(instAddr, topAddr);
         }
         else if(!strcmp(op_code, "~pr")){
             printReg();
         }
         else {
             decode(op_code, instAddr);
         }
     }
     return 1;
 }
int shutdown (int err)
Definition at line 90 of file mainB.c.
References freeMem(), MEMALLOCERROR, and NOERROR.
Referenced by hlt().
 {
     puts("Shutting down...");
     if(err == NOERROR)
     {
         puts("No errors");
         freeMem();
         return 0;
     }
     else if(err == MEMALLOCERROR)
     {
         puts("Error allocating main memory");
     }
     else
     {
         puts("Unknown error");
     }
     return -1;
 }