VM4 Simulator: main.c File Reference
main.c File Reference
#include "vm4.h"
Functions
int main (int argc, char **argv)
int mainloop (int mode)
int shutdown (int err)
Function Documentation
int main (int argc, char ** argv)
Definition at line 22 of file main.c.
References initMem(), mainloop(), readBin(), regPC, and VERSTR.
{
         int status;
     uint16_t loadLocation = 1025;
     regPC = loadLocation;
     int mode;
         printf("%s starting up...\n", VERSTR);
         printf("Command line arguments:\n");
         printf("~q: Quit, ~pm lower upper: Prints mem between lower and upper\n");
         printf("~pr: Prints register contents\n");
     printf("Enter user input mode (0), or file mode(1)?\n");
     scanf( "%d", &mode);
         for(int i = 1; i < argc; i++)
         {
                 if(argv[i] != NULL)
                 {
                         printf(" %s", argv[i]);
                 }
         }
     initMem();
         puts("");
         char fileName[100];
         if(mode  == 1){
             printf("Enter file name: ");
             scanf("%s", fileName);
         readBin(fileName, loadLocation);
     }
         status = mainloop(mode);
         return status;
 }
int mainloop (int mode)
Definition at line 63 of file main.c.
References ADD, CXA, _nibble::data, decode(), HLT, JMP, LOD, NND, NOP, printMem(), printReg(), readMem(), regA, regPC, regSTAT, setBoot(), shutdown(), STR, and UNKNOWNINSTRUCTIONERROR.
Referenced by main().
                       {
     char op_code[100];
     uint16_t instAddr;
     uint16_t topAddr;
     char run = 1;
     char in[100];
     regA.data = 0;
     regSTAT.data = 0;
     setBoot();
     char counter = 0;
     nibble currentInst;
     int tempAddress = 0;
     while(run){
         if(mode == 0)
             printf("Input: ");
         fgets(in, 99, stdin);
         sscanf(in, "%s %hu %hu", op_code, &instAddr, &topAddr);
         //Process input
         if(!strcmp(op_code, "~q")){
             printf("Halting\n");
             run = 0;
         }
         else if(!strcmp(op_code, "~pm")){
             printMem(instAddr, topAddr);
         }
         else if(!strcmp(op_code, "~pr")){
             printReg();
         }
         else {
             if(mode == 0)
                 decode(op_code, instAddr);
         }
         if(mode == 1){
             puts("Program started");
             while(!(regSTAT.data & 0x1)){
                 //Start of file code
                 currentInst = readMem(regPC);
                 instAddr = 0;
                 tempAddress = 0;
                 tempAddress = readMem(++regPC).data;
                 instAddr |= (tempAddress << 12);
                             tempAddress = readMem(++regPC).data;
                             instAddr |= (tempAddress << 8);
                             tempAddress = readMem(++regPC).data;
                             instAddr |= (tempAddress << 4);
                             tempAddress = readMem(++regPC).data;
                             instAddr |= (tempAddress);
                 regPC++;
                             if(currentInst.data == HLT)
                                     decode("HLT", instAddr);
                             else if(currentInst.data == LOD)
                                     decode("LOD", instAddr);
                             else if(currentInst.data == STR)
                                     decode("STR", instAddr);
                             else if(currentInst.data == ADD)
                                     decode("ADD", instAddr);
                             else if(currentInst.data == NOP)
                                     decode("NOP", instAddr);
                             else if(currentInst.data == NND)
                                     decode("NND", instAddr);
                             else if(currentInst.data == CXA)
                                     decode("CXA", instAddr);
                             else if(currentInst.data == JMP)
                                     decode("JMP", instAddr);
                             else
                                     shutdown(UNKNOWNINSTRUCTIONERROR);
             }
         mode = 0;
         puts("File finished");
         }
     }
     return 1;
 }
int shutdown (int err)
Definition at line 154 of file main.c.
References freeMem(), MEMALLOCERROR, NOERROR, and UNKNOWNINSTRUCTIONERROR.
Referenced by mainloop().
 {
     puts("Shutting down...");
     if(err == NOERROR)
     {
         puts("No errors");
         freeMem();
         exit(0);
     }
     else if(err == MEMALLOCERROR)
     {
         puts("Error allocating main memory");
         exit(0);
     }
     else if(err == UNKNOWNINSTRUCTIONERROR)
     {
         puts("Unknown instruction");
         exit(0);
     }
     else
     {
         puts("Unknown error");
         exit(0);
     }
     return -1;
 }