VM4 Simulator: mem.c File Reference
mem.c File Reference
#include "vm4.h"
Functions
int initmem (uint16_t num)
void walkmem (void)
void writemem (uint16_t addr, uint8_t data)
uint8_t readmem (uint16_t addr)
void freemain (void)
Variables
nib * MAINMEM = NULL
uint16_t MEMSIZE = 0
Function Documentation
void freemain (void)
Definition at line 88 of file mem.c.
References MEMSIZE.
Referenced by initmem(), and shutdown().
 {
     if(MAINMEM == NULL || MEMSIZE == 0)
     {
         return;
     }
     free(MAINMEM);
     return;
 }
int initmem (uint16_t num)
Definition at line 6 of file mem.c.
References BOOTMEM, freemain(), IOMEM, MEMSIZE, PLATEND, RESERVEMEM, and tobitstr().
Referenced by mainloop().
 {
     if(num > RESERVEMEM)
     {
         if(MAINMEM != NULL && MEMSIZE > 0)
         {
             freemain();
         }
         MAINMEM = (nib *)calloc(num, sizeof(nib));
         if(MAINMEM != NULL)
         {
             MEMSIZE = num;
             printf("Initialised %i nibbles of memory\n", MEMSIZE);
             printf("Address %s reserved for zeromem\n", tobitstr(16, 0, PLATEND));
             if(IOMEM > 0)
             {
                 printf("Bottom addresses %s to %s of memory used for I/O\n", tobitstr(16, 1, PLATEND), tobitstr(16, IOMEM, PLATEND));
             }
             if(BOOTMEM > 0)
             {
                 printf("Bottom addresses %s to %s used for boot rom\n", tobitstr(16, 1+IOMEM, PLATEND), tobitstr(16, IOMEM+BOOTMEM, PLATEND));
             }
             return num;
         }
     }
     return -1;
 }
uint8_t readmem (uint16_t addr)
Definition at line 79 of file mem.c.
References _nib::data, and MEMSIZE.
Referenced by add().
 {
     if(addr < MEMSIZE)
     {
         return MAINMEM[addr].data;
     }
     return 0;
 }
void walkmem (void)
Definition at line 35 of file mem.c.
References BOOTMEM, IOMEM, MEMADDRSIZE, MEMMODSIZE, MEMSIZE, PLATEND, and tobitstr().
Referenced by mainloop().
     {
     uint16_t loc = 0;
     if(MAINMEM == NULL || MEMSIZE == 0)
     {
         puts("No allocated memory");
         return;
     }
     puts("Memory contents:");
     for(loc = 0; loc < MEMSIZE; loc++)
     {
         printf("%s: %s", tobitstr(MEMADDRSIZE, loc, PLATEND), tobitstr(MEMMODSIZE, MAINMEM[loc].data, PLATEND));
         if(loc == 0)
         {
             printf(" (zero)");
         }
         else if(loc < IOMEM + 1 && loc > 0 && IOMEM > 0)
         {
             printf(" (I/O)");
         }
         else if(loc >= (IOMEM + 1) && loc < (1 + IOMEM + BOOTMEM) && BOOTMEM > 0)
         {
             printf(" (Boot ROM)");
         }
         puts("");
     }
 }
void writemem (uint16_t addr, uint8_t data)
Definition at line 66 of file mem.c.
References _nib::data, and MEMSIZE.
Referenced by mainloop(), and wm().
 {
     if(MAINMEM == NULL || MEMSIZE == 0)
     {
         return;
     }
     else if(addr == 0)
     {
         return;
     }
     MAINMEM[addr % MEMSIZE].data = data;
 }
Variable Documentation
nib* MAINMEM = NULL
Definition at line 3 of file mem.c.
uint16_t MEMSIZE = 0
Definition at line 4 of file mem.c.
Referenced by freemain(), initmem(), readmem(), walkmem(), and writemem().