VM4 Simulator: memB.c File Reference
memB.c File Reference
#include "vm4B.h"
Functions
int initMem (void)
void printMem (uint16_t lower, uint16_t upper)
void writeMem (nibble value, uint16_t address)
nibble readMem (uint16_t address)
void freeMem (void)
void setBoot (void)
Variables
nibble * MAINMEM = NULL
Function Documentation
void freeMem (void)
Definition at line 87 of file memB.c.
References MEMSIZE.
Referenced by shutdown().
 {
     if(MAINMEM == NULL || MEMSIZE == 0)
     {
         return;
     }
     free(MAINMEM);
     return;
 }
int initMem (void)
Definition at line 18 of file memB.c.
References MEMSIZE.
Referenced by main().
 {
     MAINMEM = (nibble*)calloc(MEMSIZE, sizeof(nibble));
     if (MAINMEM != NULL)
     {
         printf("Memory Initialized\n");
         return 1;
     }
     return -1;
 }
void printMem (uint16_t lower, uint16_t upper)
Definition at line 31 of file memB.c.
References BOOTMEM, IOMEM, MEMADDRSIZE, MEMMODSIZE, PLATEND, and tobitstr().
Referenced by mainloop().
 {
     if(MAINMEM == NULL)
     {
         puts("No allocated memory");
         return;
     }
     puts("Memory contents: ");
     for(int i = lower; i < upper ; i++)
     {
         printf("%s: %s", tobitstr(MEMADDRSIZE, i, PLATEND), tobitstr(MEMMODSIZE, MAINMEM[i].data, PLATEND));
         if(i < IOMEM && IOMEM > 0)
         {
             printf(" (I/O)");
         }
         else if(i >= (IOMEM) && i < (IOMEM + BOOTMEM) && BOOTMEM > 0)
         {
             printf(" (Boot ROM)");
         }
         puts("");
     }
 }
nibble readMem (uint16_t address)
Definition at line 75 of file memB.c.
References MEMSIZE.
 {
     if(address < MEMSIZE)
     {
         return MAINMEM[address];
     }
     printf("WARNING Address accessed was negative");
     nibble n;
     return n;
 }
void setBoot (void)
Definition at line 98 of file memB.c.
References _nibble::data, and IOMEM.
Referenced by mainloop().
                   {
     for(int i = 0; i < 16; i++){
         MAINMEM[i+IOMEM].data = i;
     }
 }
void writeMem (nibble value, uint16_t address)
Definition at line 61 of file memB.c.
References _nibble::data, and MEMSIZE.
 {
     if(MAINMEM == NULL)
     {
         return;
     }
     else if(address < 3)
     {
         return;
     }
     MAINMEM[address % MEMSIZE].data = value.data;
 }
Variable Documentation
nibble* MAINMEM = NULL
Definition at line 15 of file memB.c.
Referenced by add(), lod(), nnd(), and str().