VM4 Simulator: reg.c File Reference
reg.c File Reference
#include "vm4.h"
Functions
void initreg (void)
void writereg (unsigned int reg, uint8_t data)
void walkreg (void)
uint8_t readreg (unsigned int reg)
Variables
nib REGBANK [5]
Function Documentation
void initreg (void)
Definition at line 5 of file reg.c.
References _nib::data, and NUMREG.
Referenced by mainloop().
 {
     int i = 0;
     for(i = 0; i < NUMREG; i++)
     {
         REGBANK[i].data = 0;
     }
 }
uint8_t readreg (unsigned int reg)
Definition at line 55 of file reg.c.
References _nib::data, and NUMREG.
Referenced by add(), mv(), and wm().
 {
     if(reg < NUMREG)
     {
         return REGBANK[reg].data;
     }
     return 0;
 }
void walkreg (void)
Definition at line 22 of file reg.c.
References A, M1, M2, M3, M4, NUMREG, PLATEND, REGSIZE, and tobitstr().
Referenced by mainloop().
 {
     int i;
     puts("Register contents:");
     for(i = 0; i < NUMREG; i++)
     {
         if(i == A)
         {
             printf("Accumulator: %s\n", tobitstr(REGSIZE, REGBANK[A].data, PLATEND));
         }
         else if(i == M1)
         {
             printf("Memory pointer lowest nibble: %s\n", tobitstr(REGSIZE, REGBANK[M1].data, PLATEND));
         }
         else if(i == M2)
         {
             printf("Memory pointer low-mid nibble: %s\n", tobitstr(REGSIZE, REGBANK[M2].data, PLATEND));
         }
         else if(i == M3)
         {
             printf("Memory pointer high-mid nibble: %s\n", tobitstr(REGSIZE, REGBANK[M3].data, PLATEND));
         }
         else if(i == M4)
         {
             printf("Memory pointer highest nibble: %s\n", tobitstr(REGSIZE, REGBANK[M4].data, PLATEND));
         }
     }
 }
void writereg (unsigned int reg, uint8_t data)
Definition at line 14 of file reg.c.
References _nib::data, and NUMREG.
Referenced by add(), li(), mainloop(), and mv().
 {
     if(reg < NUMREG)
     {
         REGBANK[reg].data = data % 16;
     }
 }
Variable Documentation
nib REGBANK[5]
Definition at line 3 of file reg.c.