VM4 Simulator: util.c File Reference
util.c File Reference
#include "vm4.h"
Functions
char * tobitstr (size_t size, uint64_t data, char dir)
uint16_t toaddr (char *str)
uint8_t todata (char *str)
unsigned int toreg (char *str)
Function Documentation
uint16_t toaddr (char * str)
Definition at line 40 of file util.c.
Referenced by mainloop().
 {
     return (uint16_t) strtol(str, NULL, 0);
 }
char* tobitstr (size_t size, uint64_t data, char dir)
Definition at line 5 of file util.c.
References BIGEND, and LITTLEEND.
Referenced by initmem(), walkmem(), and walkreg().
 {
     uint64_t i, j;
     char *str = NULL;
     str = calloc(size, 1);
     if(str == NULL)
     {
         return NULL;
     }
     if(dir == LITTLEEND)
     {
         for(i = (pow(2,size - 1)), j = 0; i > 0; i >>= 1, j++)
         {
             if(j % 4 == 0 && j != 0)
             {
                 strcat(str, " ");
             }
             strcat(str, ((data & i) == i) ? "1" : "0");
         }
     }
     else if(dir == BIGEND)
     {
         for(i = 1, j = 0; (i < (pow(2,size)) - 1 && i != 0); i <<= 1, j++)
         {
             if(j % 4 == 0 && j != 0)
             {
                 strcat(str, " ");
             }
             strcat(str, ((data & i) == i) ? "1" : "0");
         }
     }
     return str;
 }
uint8_t todata (char * str)
Definition at line 45 of file util.c.
Referenced by mainloop(), and readinst().
 {
     return (uint8_t) (strtol(str, NULL, 0) % 16);
 }
unsigned int toreg (char * str)
Definition at line 50 of file util.c.
References A, INSTLEN, M1, M2, M3, and M4.
Referenced by mainloop(), and readinst().
 {
     if(!strncmp(str, "a", INSTLEN - 1))
     {
         return A;
     }
     else if(!strncmp(str, "mem.lo", INSTLEN - 1))
     {
         return M1;
     }
     else if(!strncmp(str, "mem.midlo", INSTLEN - 1))
     {
         return M2;
     }
     else if(!strncmp(str, "mem.midhi", INSTLEN - 1))
     {
         return M3;
     }
     else if(!strncmp(str, "mem.hi", INSTLEN - 1))
     {
         return M4;
     }
     return 0;
 }