VM4 Simulator: vm4.h File Reference
vm4.h File Reference
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <limits.h>
#include <inttypes.h>
#include <time.h>
Data Structures
struct _nibble
Macros
#define VERSTR "VM4 v0.3"
#define BOOTBIN "test.bin"
#define IOMEM 3
#define BOOTMEM 1024
#define RESERVEMEM (1 + IOMEM + BOOTMEM)
#define NOERROR 0
#define MEMALLOCERROR 1
#define UNKNOWNINSTRUCTIONERROR 2
#define UNKOWNERROR -1
#define MEMADDRSIZE 16
#define MEMSIZE 65536
#define BIGEND -1
#define LITTLEEND 1
#define MEMMODSIZE 4
#define PLATEND LITTLEEND
#define NUMREG 4
#define PC 0
#define A 1
#define MEM 2
#define STAT 3
#define HLT 0
#define LOD 1
#define STR 2
#define ADD 3
#define NOP 4
#define NND 5
#define JMP 6
#define CXA 7
#define REGISTER16BIT 0
#define REGISTER4BIT 1
Typedefs
typedef struct _nibble nibble
Functions
int decode (const char *op_code, uint16_t address)
void hlt (void)
void lod (uint16_t)
void str (uint16_t)
void add (uint16_t)
void nop (void)
void nnd (uint16_t)
void cxa (void)
void jmp (uint16_t)
void printReg (void)
void setXOR (void)
int initMem (void)
nibble readMem (uint16_t)
void writeMem (nibble data, uint16_t address)
void printMem (uint16_t, uint16_t)
void freeMem (void)
void setBoot (void)
int mainloop (int mode)
int shutdown (int)
char * tobitstr (size_t, uint64_t, char)
int readBin (const char *, uint16_t)
Variables
uint16_t regPC
nibble regA
uint16_t regMEM
nibble regSTAT
nibble * MAINMEM
Macro Definition Documentation
#define A 1
Definition at line 44 of file vm4.h.
#define ADD 3
Definition at line 51 of file vm4.h.
Referenced by mainloop().
#define BIGEND -1
Definition at line 36 of file vm4.h.
Referenced by tobitstr().
#define BOOTBIN "test.bin"
Definition at line 26 of file vm4.h.
#define BOOTMEM 1024
Definition at line 28 of file vm4.h.
Referenced by printMem().
#define CXA 7
Definition at line 55 of file vm4.h.
Referenced by mainloop().
#define HLT 0
Definition at line 48 of file vm4.h.
Referenced by mainloop().
#define IOMEM 3
Definition at line 27 of file vm4.h.
Referenced by printMem(), and setBoot().
#define JMP 6
Definition at line 54 of file vm4.h.
Referenced by mainloop().
#define LITTLEEND 1
Definition at line 37 of file vm4.h.
Referenced by tobitstr().
#define LOD 1
Definition at line 49 of file vm4.h.
Referenced by mainloop().
#define MEM 2
Definition at line 45 of file vm4.h.
#define MEMADDRSIZE 16
Definition at line 34 of file vm4.h.
Referenced by printMem().
#define MEMALLOCERROR 1
Definition at line 31 of file vm4.h.
Referenced by shutdown().
#define MEMMODSIZE 4
Definition at line 38 of file vm4.h.
Referenced by printMem().
#define MEMSIZE 65536
Definition at line 35 of file vm4.h.
Referenced by freeMem(), initMem(), readMem(), and writeMem().
#define NND 5
Definition at line 53 of file vm4.h.
Referenced by mainloop().
#define NOERROR 0
Definition at line 30 of file vm4.h.
Referenced by shutdown().
#define NOP 4
Definition at line 52 of file vm4.h.
Referenced by mainloop().
#define NUMREG 4
Definition at line 42 of file vm4.h.
#define PC 0
Definition at line 43 of file vm4.h.
#define PLATEND LITTLEEND
Definition at line 40 of file vm4.h.
Referenced by printMem().
#define REGISTER16BIT 0
Definition at line 58 of file vm4.h.
#define REGISTER4BIT 1
Definition at line 59 of file vm4.h.
#define RESERVEMEM (1 + IOMEM + BOOTMEM)
Definition at line 29 of file vm4.h.
#define STAT 3
Definition at line 46 of file vm4.h.
#define STR 2
Definition at line 50 of file vm4.h.
Referenced by mainloop().
#define UNKNOWNINSTRUCTIONERROR 2
Definition at line 32 of file vm4.h.
Referenced by mainloop(), and shutdown().
#define UNKOWNERROR -1
Definition at line 33 of file vm4.h.
#define VERSTR "VM4 v0.3"
Definition at line 25 of file vm4.h.
Referenced by main().
Typedef Documentation
typedef struct _nibble nibble
Function Documentation
void add (uint16_t)
Definition at line 80 of file inst.c.
References _nibble::data, MAINMEM, and regMEM.
Referenced by decode().
{
     regMEM = addAddress;
     uint8_t temp1 = regA.data;
     uint8_t temp2 = MAINMEM[addAddress].data;
     uint8_t result = temp1 + temp2;
     regA.data = result & 0xF;
     //Set overflow bit
     if((temp1 & 0x8) && (temp2 & 0x8) && !(result & 0x8)){
         regSTAT.data |= 0x8;
         regSTAT.data ^= (result & 0x8);
         }
     else if(!(temp1 & 0x8) && !(temp2 & 0x8) && (result & 0x8)){
         regSTAT.data |= 0x8;
         regSTAT.data ^= (result & 0x8);
         }
     else
         regSTAT.data &= 0x7;
     //If there was a carry out
     if(result & 0x10)
         regSTAT.data |= 0x2;
     else
         regSTAT.data &= 0xD;
 }
void cxa (void)
Definition at line 118 of file inst.c.
References _nibble::data.
Referenced by decode().
               {
     regA.data = regSTAT.data;
 }
int decode (const char * op_code, uint16_t address)
Definition at line 26 of file inst.c.
References add(), cxa(), hlt(), jmp(), lod(), nnd(), nop(), and str().
Referenced by mainloop().
 {
     if(!strcmp(op_code, "HLT"))
     {
         hlt();
     }
     else if(!strcmp(op_code, "LOD"))
     {
         lod(address);
     }
     else if(!strcmp(op_code, "STR"))
     {
         str(address);
     }
     else if(!strcmp(op_code, "ADD"))
     {
         add(address);
     }
     else if(!strcmp(op_code, "NOP"))
     {
         nop();
     }
     else if(!strcmp(op_code, "NND"))
     {
         nnd(address);
     }
     else if(!strcmp(op_code, "JMP"))
     {
         jmp(address);
     }
     else if(!strcmp(op_code, "CXA"))
     {
         cxa();
     }
     return 0;
 }
void freeMem (void)
Definition at line 87 of file mem.c.
References MEMSIZE.
Referenced by shutdown().
 {
     if(MAINMEM == NULL || MEMSIZE == 0)
     {
         return;
     }
     free(MAINMEM);
     return;
 }
void hlt (void)
Definition at line 65 of file inst.c.
References _nibble::data.
Referenced by decode().
               {
     regSTAT.data |= 0x1;
 }
int initMem (void)
Definition at line 18 of file mem.c.
References MEMSIZE.
Referenced by main().
 {
     MAINMEM = (nibble*)calloc(MEMSIZE, sizeof(nibble));
     if (MAINMEM != NULL)
     {
         printf("Memory Initialized\n");
         return 1;
     }
     return -1;
 }
void jmp (uint16_t)
Definition at line 122 of file inst.c.
References _nibble::data, regMEM, and regPC.
Referenced by decode().
{
     regMEM = jumpAddress;
     if(regA.data == 0)
         regPC = jumpAddress;
 }
void lod (uint16_t)
Definition at line 69 of file inst.c.
References MAINMEM, and regMEM.
Referenced by decode().
{
     regMEM = addressFrom;
     regA = MAINMEM[addressFrom];
     //setXOR(); No longer doing this in load
 }
int mainloop (int mode)
Definition at line 67 of file main.c.
References ADD, CXA, _nibble::data, decode(), HLT, JMP, LOD, NND, NOP, printMem(), printReg(), readMem(), regA, regPC, regSTAT, setBoot(), shutdown(), STR, and UNKNOWNINSTRUCTIONERROR.
Referenced by main().
                       {
     char op_code[100];
     uint16_t instAddr;
     uint16_t topAddr;
     char run = 1;
     char in[100];
     regA.data = 0;
     regSTAT.data = 0;
     setBoot();
     char counter = 0;
     nibble currentInst;
     int tempAddress = 0;
     struct timespec gettime_now;
     double firstTime;
     double secondTime;
     while(run){
         if(mode == 0)
             printf("Input: ");
         fgets(in, 99, stdin);
         sscanf(in, "%s %hu %hu", op_code, &instAddr, &topAddr);
         //Process input
         if(!strcmp(op_code, "~q")){
             printf("Halting\n");
             run = 0;
         }
         else if(!strcmp(op_code, "~pm")){
             printMem(instAddr, topAddr);
         }
         else if(!strcmp(op_code, "~pr")){
             printReg();
         }
         else {
             if(mode == 0)
                 decode(op_code, instAddr);
         }
         if(mode == 1){
             puts("Program started");
             while(!(regSTAT.data & 0x1)){
                 //Start of file code
                 clock_gettime(CLOCK_REALTIME, &gettime_now);
                 firstTime = gettime_now.tv_nsec;
                 currentInst = readMem(regPC);
                 instAddr = 0;
                 tempAddress = 0;
                 tempAddress = readMem(++regPC).data;
                 instAddr |= (tempAddress << 12);
                             tempAddress = readMem(++regPC).data;
                             instAddr |= (tempAddress << 8);
                             tempAddress = readMem(++regPC).data;
                             instAddr |= (tempAddress << 4);
                             tempAddress = readMem(++regPC).data;
                             instAddr |= (tempAddress);
                 regPC++;
                             if(currentInst.data == HLT)
                                     decode("HLT", instAddr);
                             else if(currentInst.data == LOD)
                                     decode("LOD", instAddr);
                             else if(currentInst.data == STR)
                                     decode("STR", instAddr);
                             else if(currentInst.data == ADD)
                                     decode("ADD", instAddr);
                             else if(currentInst.data == NOP)
                                     decode("NOP", instAddr);
                             else if(currentInst.data == NND)
                                     decode("NND", instAddr);
                             else if(currentInst.data == CXA)
                                     decode("CXA", instAddr);
                             else if(currentInst.data == JMP)
                                     decode("JMP", instAddr);
                             else
                                     shutdown(UNKNOWNINSTRUCTIONERROR);
                 clock_gettime(CLOCK_REALTIME, &gettime_now);
                 secondTime = gettime_now.tv_nsec - firstTime;
                 printf("Time taken for instruction: %f", secondTime);
             }
         mode = 0;
         puts("Program finished");
         }
     }
     return 1;
 }
void nnd (uint16_t)
Definition at line 111 of file inst.c.
References _nibble::data, MAINMEM, and regMEM.
Referenced by decode().
{
     regMEM = nndAddress;
     regA.data &= MAINMEM[nndAddress].data;
     regA.data = ~regA.data;
     //setXOR();
 }
void nop (void)
Definition at line 107 of file inst.c.
Referenced by decode().
               {
 }
void printMem (uint16_t , uint16_t)
Definition at line 31 of file mem.c.
References BOOTMEM, IOMEM, MEMADDRSIZE, MEMMODSIZE, PLATEND, and tobitstr().
Referenced by mainloop().
 {
     if(MAINMEM == NULL)
     {
         puts("No allocated memory");
         return;
     }
     puts("Memory contents: ");
     for(int i = lower; i < upper ; i++)
     {
         printf("%s: %s", tobitstr(MEMADDRSIZE, i, PLATEND), tobitstr(MEMMODSIZE, MAINMEM[i].data, PLATEND));
         if(i < IOMEM && IOMEM > 0)
         {
             printf(" (I/O)");
         }
         else if(i >= (IOMEM) && i < (IOMEM + BOOTMEM) && BOOTMEM > 0)
         {
             printf(" (Boot ROM)");
         }
         puts("");
     }
 }
void printReg (void)
Definition at line 129 of file inst.c.
References _nibble::data, regMEM, and regPC.
Referenced by mainloop().
                    {
     printf("A: %x\n", regA.data);
     printf("PC: %x\n", regPC);
     printf("MEM: %x\n", regMEM);
     printf("STAT: %x\n", regSTAT.data);
 }
int readBin (const char * , uint16_t)
Definition at line 17 of file fileIO.c.
References _nibble::data, and writeMem().
Referenced by main().
{
     unsigned char buffer = 0;
     nibble temp2;
     nibble temp;
     int counter = 0;
     FILE *binFilePtr;
     printf("Reading Boot file...\n");
     //Open the Bin File
     binFilePtr = fopen(fileName, "rb");
     if(!binFilePtr){
         printf("Unable to open .bin file\n");
         return 1;
     }
     while(1){
         //Read a nibble at a time
         fread(&buffer, sizeof(buffer), 1, binFilePtr);
         temp.data = buffer;
         //Check for end of File
         if(feof(binFilePtr))
             break;
         //Store in Mem
         temp2.data = (buffer >> 4);
         writeMem( temp2, memLocation );
         memLocation += 1;
         writeMem(temp, memLocation);
         memLocation++;
         counter++; counter++;
     }
     fclose(binFilePtr);
     printf("Finished Boot\n");
     return counter/5;
 }
nibble readMem (uint16_t)
Definition at line 75 of file mem.c.
References MEMSIZE.
Referenced by mainloop().
 {
     if(address < MEMSIZE)
     {
         return MAINMEM[address];
     }
     printf("WARNING Address accessed was negative");
     nibble n;
     return n;
 }
void setBoot (void)
Definition at line 98 of file mem.c.
References _nibble::data, and IOMEM.
Referenced by mainloop().
                   {
     for(int i = 0; i < 16; i++){
         MAINMEM[i+IOMEM].data = i;
     }
 }
void setXOR (void)
Definition at line 138 of file inst.c.
References _nibble::data.
                  {
         nibble temp;
         temp.data = regA.data ^ regSTAT.data;
         temp.data &=  0x8;
         if(temp.data == 0x8)
             regSTAT.data |= 0x2;
         else
             regSTAT.data &= 0xD;
 }
int shutdown (int)
Definition at line 167 of file main.c.
References freeMem(), MEMALLOCERROR, NOERROR, and UNKNOWNINSTRUCTIONERROR.
Referenced by mainloop().
 {
     puts("Shutting down...");
     if(err == NOERROR)
     {
         puts("No errors");
         freeMem();
         exit(0);
     }
     else if(err == MEMALLOCERROR)
     {
         puts("Error allocating main memory");
         exit(0);
     }
     else if(err == UNKNOWNINSTRUCTIONERROR)
     {
         puts("Unknown instruction");
         exit(0);
     }
     else
     {
         puts("Unknown error");
         exit(0);
     }
     return -1;
 }
void str (uint16_t)
Definition at line 75 of file inst.c.
References MAINMEM, regA, and regMEM.
Referenced by decode(), and tobitstr().
{
     regMEM = addressTo;
     MAINMEM[addressTo] =  regA;
 }
char* tobitstr (size_t , uint64_t , char)
Definition at line 5 of file util.c.
References BIGEND, LITTLEEND, and str().
Referenced by printMem().
 {
     uint64_t i, j;
     char *str = NULL;
     str = calloc(size, 1);
     if(str == NULL)
     {
         return NULL;
     }
     if(dir == LITTLEEND)
     {
         for(i = (pow(2,size - 1)), j = 0; i > 0; i >>= 1, j++)
         {
             if(j % 4 == 0 && j != 0)
             {
                 strcat(str, " ");
             }
             strcat(str, ((data & i) == i) ? "1" : "0");
         }
     }
     else if(dir == BIGEND)
     {
         for(i = 1, j = 0; (i < (pow(2,size)) - 1 && i != 0); i <<= 1, j++)
         {
             if(j % 4 == 0 && j != 0)
             {
                 strcat(str, " ");
             }
             strcat(str, ((data & i) == i) ? "1" : "0");
         }
     }
     return str;
 }
void writeMem (nibble data, uint16_t address)
Definition at line 61 of file mem.c.
References _nibble::data, and MEMSIZE.
Referenced by readBin().
 {
     if(MAINMEM == NULL)
     {
         return;
     }
     else if(address < 3)
     {
         return;
     }
     MAINMEM[address % MEMSIZE].data = value.data;
 }
Variable Documentation
nibble* MAINMEM
Definition at line 15 of file mem.c.
Referenced by add(), lod(), nnd(), and str().
nibble regA
Definition at line 18 of file inst.c.
Referenced by mainloop(), and str().
uint16_t regMEM
Definition at line 19 of file inst.c.
Referenced by add(), jmp(), lod(), nnd(), printReg(), and str().
uint16_t regPC
Definition at line 17 of file inst.c.
Referenced by jmp(), main(), mainloop(), and printReg().
nibble regSTAT
Definition at line 20 of file inst.c.
Referenced by mainloop().