VM4 Simulator: vm4B.h File Reference
vm4B.h File Reference
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <limits.h>
#include <inttypes.h>
Data Structures
struct _nibble
Macros
#define VERSTR "VM4 v0.1"
#define IOMEM 3
#define BOOTMEM 1024
#define RESERVEMEM (1 + IOMEM + BOOTMEM)
#define NOERROR 0
#define MEMALLOCERROR 1
#define UNKOWNERROR -1
#define MEMADDRSIZE 16
#define MEMSIZE 65536
#define BIGEND -1
#define LITTLEEND 1
#define MEMMODSIZE 4
#define PLATEND LITTLEEND
#define NUMREG 4
#define PC 0
#define A 1
#define MEM 2
#define STAT 3
#define HLT 0
#define LOD 1
#define STR 2
#define ADD 3
#define NOP 4
#define NND 5
#define JMP 6
#define CXA 7
#define REGISTER16BIT 0
#define REGISTER4BIT 1
Typedefs
typedef struct _nibble nibble
Functions
int mainloop (void)
int decode (char *op_code, uint16_t address)
void hlt (void)
void lod (uint16_t)
void str (uint16_t)
void add (uint16_t)
void nop (void)
void nnd (uint16_t)
void cxa (void)
void jmp (uint16_t)
void printReg (void)
void setXOR (void)
int initMem (void)
void writeMem (nibble data, uint16_t address)
void printMem (uint16_t, uint16_t)
void freeMem (void)
void setBoot (void)
int shutdown (int)
char * tobitstr (size_t, uint64_t, char)
Variables
uint16_t regPC
nibble regA
uint16_t regMEM
nibble regSTAT
nibble * MAINMEM
Macro Definition Documentation
#define A 1
Definition at line 40 of file vm4B.h.
#define ADD 3
Definition at line 47 of file vm4B.h.
#define BIGEND -1
Definition at line 32 of file vm4B.h.
Referenced by tobitstr().
#define BOOTMEM 1024
Definition at line 25 of file vm4B.h.
Referenced by printMem().
#define CXA 7
Definition at line 51 of file vm4B.h.
#define HLT 0
Definition at line 44 of file vm4B.h.
#define IOMEM 3
Definition at line 24 of file vm4B.h.
Referenced by printMem(), and setBoot().
#define JMP 6
Definition at line 50 of file vm4B.h.
#define LITTLEEND 1
Definition at line 33 of file vm4B.h.
Referenced by tobitstr().
#define LOD 1
Definition at line 45 of file vm4B.h.
#define MEM 2
Definition at line 41 of file vm4B.h.
#define MEMADDRSIZE 16
Definition at line 30 of file vm4B.h.
Referenced by printMem().
#define MEMALLOCERROR 1
Definition at line 28 of file vm4B.h.
Referenced by shutdown().
#define MEMMODSIZE 4
Definition at line 34 of file vm4B.h.
Referenced by printMem().
#define MEMSIZE 65536
Definition at line 31 of file vm4B.h.
Referenced by freeMem(), initMem(), readMem(), and writeMem().
#define NND 5
Definition at line 49 of file vm4B.h.
#define NOERROR 0
Definition at line 27 of file vm4B.h.
Referenced by hlt(), and shutdown().
#define NOP 4
Definition at line 48 of file vm4B.h.
#define NUMREG 4
Definition at line 38 of file vm4B.h.
#define PC 0
Definition at line 39 of file vm4B.h.
#define PLATEND LITTLEEND
Definition at line 36 of file vm4B.h.
Referenced by printMem().
#define REGISTER16BIT 0
Definition at line 54 of file vm4B.h.
#define REGISTER4BIT 1
Definition at line 55 of file vm4B.h.
#define RESERVEMEM (1 + IOMEM + BOOTMEM)
Definition at line 26 of file vm4B.h.
#define STAT 3
Definition at line 42 of file vm4B.h.
#define STR 2
Definition at line 46 of file vm4B.h.
#define UNKOWNERROR -1
Definition at line 29 of file vm4B.h.
#define VERSTR "VM4 v0.1"
Definition at line 23 of file vm4B.h.
Referenced by main().
Typedef Documentation
typedef struct _nibble nibble
Function Documentation
void add (uint16_t)
Definition at line 78 of file instB.c.
References _nibble::data, MAINMEM, and setXOR().
Referenced by decode().
{
     uint8_t temp1 = regA.data;
     uint8_t temp2 = MAINMEM[addAddress].data;
     uint8_t result = temp1 + temp2;
     if((result & 0x10) == 0x10)
         regSTAT.data |= 0x8;
     else
         regSTAT.data &= 0x7;
     regA.data = result & 0xF;
     setXOR();
 }
void cxa (void)
Definition at line 100 of file instB.c.
References _nibble::data.
Referenced by decode().
               {
     regA.data = regSTAT.data;
 }
int decode (char * op_code, uint16_t address)
Definition at line 26 of file instB.c.
References add(), cxa(), hlt(), jmp(), lod(), nnd(), nop(), and str().
Referenced by mainloop().
 {
     if(!strcmp(op_code, "HLT"))
     {
         hlt();
     }
     else if(!strcmp(op_code, "LOD"))
     {
         lod(address);
     }
     else if(!strcmp(op_code, "STR"))
     {
         str(address);
     }
     else if(!strcmp(op_code, "ADD"))
     {
         add(address);
     }
     else if(!strcmp(op_code, "NOP"))
     {
         nop();
     }
     else if(!strcmp(op_code, "NND"))
     {
         nnd(address);
     }
     else if(!strcmp(op_code, "JMP"))
     {
         jmp(address);
     }
     else if(!strcmp(op_code, "CXA"))
     {
         cxa();
     }
     return 0;
 }
void freeMem (void)
Definition at line 87 of file memB.c.
References MEMSIZE.
Referenced by shutdown().
 {
     if(MAINMEM == NULL || MEMSIZE == 0)
     {
         return;
     }
     free(MAINMEM);
     return;
 }
void hlt (void)
Definition at line 65 of file instB.c.
References NOERROR, and shutdown().
Referenced by decode().
               {
     shutdown(NOERROR);
 }
int initMem (void)
Definition at line 18 of file memB.c.
References MEMSIZE.
Referenced by main().
 {
     MAINMEM = (nibble*)calloc(MEMSIZE, sizeof(nibble));
     if (MAINMEM != NULL)
     {
         printf("Memory Initialized\n");
         return 1;
     }
     return -1;
 }
void jmp (uint16_t)
Definition at line 104 of file instB.c.
References _nibble::data, and regPC.
Referenced by decode().
{
     if(regA.data == 0)
         regPC = jumpAddress;
 }
void lod (uint16_t)
Definition at line 69 of file instB.c.
References MAINMEM, and setXOR().
Referenced by decode().
{
     regA = MAINMEM[addressFrom];
     setXOR();
 }
int mainloop (void)
Definition at line 48 of file mainB.c.
References _nibble::data, decode(), printMem(), printReg(), regA, regSTAT, and setBoot().
Referenced by main().
                   {
     char op_code[100];
     uint16_t instAddr;
     uint16_t topAddr;
     char run = 1;
     char in[100];
     regA.data = 0;
     regSTAT.data = 0;
     setBoot();
     while(run){
         printf("Input: ");
         fgets(in, 99, stdin);
         sscanf(in, "%s %hu %hu", op_code, &instAddr, &topAddr);
         //Process input
         if(!strcmp(op_code, "~q")){
             printf("Halting");
             run = 0;
         }
         else if(!strcmp(op_code, "~pm")){
             printMem(instAddr, topAddr);
         }
         else if(!strcmp(op_code, "~pr")){
             printReg();
         }
         else {
             decode(op_code, instAddr);
         }
     }
     return 1;
 }
void nnd (uint16_t)
Definition at line 94 of file instB.c.
References _nibble::data, MAINMEM, and setXOR().
Referenced by decode().
{
     regA.data &= MAINMEM[nndAddress].data;
     regA.data = ~regA.data;
     setXOR();
 }
void nop (void)
Definition at line 90 of file instB.c.
Referenced by decode().
               {
 }
void printMem (uint16_t , uint16_t)
Definition at line 31 of file memB.c.
References BOOTMEM, IOMEM, MEMADDRSIZE, MEMMODSIZE, PLATEND, and tobitstr().
Referenced by mainloop().
 {
     if(MAINMEM == NULL)
     {
         puts("No allocated memory");
         return;
     }
     puts("Memory contents: ");
     for(int i = lower; i < upper ; i++)
     {
         printf("%s: %s", tobitstr(MEMADDRSIZE, i, PLATEND), tobitstr(MEMMODSIZE, MAINMEM[i].data, PLATEND));
         if(i < IOMEM && IOMEM > 0)
         {
             printf(" (I/O)");
         }
         else if(i >= (IOMEM) && i < (IOMEM + BOOTMEM) && BOOTMEM > 0)
         {
             printf(" (Boot ROM)");
         }
         puts("");
     }
 }
void printReg (void)
Definition at line 110 of file instB.c.
References _nibble::data, regMEM, and regPC.
Referenced by mainloop().
                    {
     printf("A: %x\n", regA.data);
     printf("PC: %x\n", regPC);
     printf("MEM: %x\n", regMEM);
     printf("STAT: %x\n", regSTAT.data);
 }
void setBoot (void)
Definition at line 98 of file memB.c.
References _nibble::data, and IOMEM.
Referenced by mainloop().
                   {
     for(int i = 0; i < 16; i++){
         MAINMEM[i+IOMEM].data = i;
     }
 }
void setXOR (void)
Definition at line 119 of file instB.c.
References _nibble::data.
Referenced by add(), lod(), and nnd().
                  {
         nibble temp;
         temp.data = regA.data ^ regSTAT.data;
         temp.data &=  0x8;
         if(temp.data == 0x8)
             regSTAT.data |= 0x2;
         else
             regSTAT.data &= 0xD;
 }
int shutdown (int)
Definition at line 90 of file mainB.c.
References freeMem(), MEMALLOCERROR, and NOERROR.
Referenced by hlt().
 {
     puts("Shutting down...");
     if(err == NOERROR)
     {
         puts("No errors");
         freeMem();
         return 0;
     }
     else if(err == MEMALLOCERROR)
     {
         puts("Error allocating main memory");
     }
     else
     {
         puts("Unknown error");
     }
     return -1;
 }
void str (uint16_t)
Definition at line 74 of file instB.c.
References MAINMEM, and regA.
Referenced by decode(), and tobitstr().
{
     MAINMEM[addressTo] =  regA;
 }
char* tobitstr (size_t , uint64_t , char)
Definition at line 5 of file util.c.
References BIGEND, LITTLEEND, and str().
Referenced by printMem().
 {
     uint64_t i, j;
     char *str = NULL;
     str = calloc(size, 1);
     if(str == NULL)
     {
         return NULL;
     }
     if(dir == LITTLEEND)
     {
         for(i = (pow(2,size - 1)), j = 0; i > 0; i >>= 1, j++)
         {
             if(j % 4 == 0 && j != 0)
             {
                 strcat(str, " ");
             }
             strcat(str, ((data & i) == i) ? "1" : "0");
         }
     }
     else if(dir == BIGEND)
     {
         for(i = 1, j = 0; (i < (pow(2,size)) - 1 && i != 0); i <<= 1, j++)
         {
             if(j % 4 == 0 && j != 0)
             {
                 strcat(str, " ");
             }
             strcat(str, ((data & i) == i) ? "1" : "0");
         }
     }
     return str;
 }
void writeMem (nibble data, uint16_t address)
Definition at line 61 of file memB.c.
References _nibble::data, and MEMSIZE.
 {
     if(MAINMEM == NULL)
     {
         return;
     }
     else if(address < 3)
     {
         return;
     }
     MAINMEM[address % MEMSIZE].data = value.data;
 }
Variable Documentation
nibble* MAINMEM
Definition at line 15 of file memB.c.
Referenced by add(), lod(), nnd(), and str().
nibble regA
Definition at line 18 of file instB.c.
Referenced by mainloop(), and str().
uint16_t regMEM
Definition at line 19 of file instB.c.
Referenced by printReg().
uint16_t regPC
Definition at line 17 of file instB.c.
Referenced by jmp(), and printReg().
nibble regSTAT
Definition at line 20 of file instB.c.
Referenced by mainloop().